[workspace]

members = [
  "problem1",
  "problem2",
  "problem3",
  "problem4",
  "problem5",
  "problem6",
  "problem7",
  "problem8",
  "problem9",
  "problem10",
  "problem11",
  "problem18",
  "problem19",
  "problem21",
  "problem22",
  "problem24",
  "problem67",
]
